### ISSUE TITLE
Can't access the file

### ISSUE THREAD

**Issue by sneha1sahu** [warden/bitbucket-tomcat-deploy-pipe#2]
why while buIlding I am getting an error as 

Unable to find image 'warden/bitbucket-tomcat-deploy-pipe:1.0' locally

Can't access the file /opt/atlassian/pipelines/agent/build/appname.war

**Comment by warden** [comment]
You need to pass the artifact from the previous build step, example for a NodeJS project:
```
- step:
    name: Build  ## build and pass the appname.war to deploy step
    script:
      - yarn build
    artifacts:
      - build/**
- step:
    name: Deploy to Tomcat
    deployment: dev
    script:
      - pipe: docker://warden/bitbucket-tomcat-deploy-pipe:1.0
        variables:
          DEPLOY_FILE: /opt/atlassian/pipelines/agent/build/appname.war
          DEPLOY_PATH: /appname
          URL: $TOMCAT_URL
          USER: $TOMCAT_USER
          PASS: $TOMCAT_PASS
```
